version: '3.8'
services:
    frontend:
        build: 
          context: ./frontend
          target: development_stage
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING="true"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        tty: true
        expose:
            - 3000
        networks:
            - frontend