version: '3.8'
services:
    proxy:
        extends:
            file: docker-compose.base.yaml
            service: proxy
        container_name: proxy
        hostname: proxy
        networks:
            - frontend
        depends_on:
            - frontend
            - backend
        volumes:
            - ./configuration/nginx.local.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    frontend:
        container_name: frontend
        hostname: frontend
        restart: unless-stopped
        build: 
          context: ./frontend
          target: development_stage
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING="true"
        env_file:
            - .env
        volumes:
            - ./frontend:/app
            - /app/node_modules
        tty: true
        expose:
            - 3000
        networks:
            - frontend
    backend:
        extends:
            file: docker-compose.base.yaml
            service: backend
        command: "/start-reload.sh"
networks:
    frontend:
    backend: