version: '3.8'
services:
    proxy:
        extends:
            file: docker-compose.base.yaml
            service: proxy
        container_name: proxy_frontend
        hostname: proxy_frontend
        restart: unless-stopped
        build: 
          context: ./frontend
          target: production_stage
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        volumes:
            - ./configuration/nginx.conf:/etc/nginx/nginx.conf
        tty: true
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        extends:
            file: docker-compose.base.yaml
            service: backend
networks:
    backend: