version: '3.8'
services:
    proxy:
        build: 
          context: ./frontend
          target: production_stage
        environment:
            - NODE_ENV=production
            - REACT_APP_API=$API_ENDPOINT
        volumes:
            - ./configuration/nginx.conf:/etc/nginx/nginx.conf
        tty: true
        ports:
            - 80:80
        networks:
            - frontend
        depends_on: 
            - backend
networks:
    frontend: