version: '2'
services: 
    # nginx: 
    #     image: nginx:alpine
    #     ports:
    #         - "80:80"
    #         - "8000:8000"

    frontend:
        build: ./frontend
        environment:
          - NODE_ENV=development
        ports:
          - 80:3000
        volumes:
          - ./frontend:/app
          - /app/node_modules
        tty: true
        
    backend:
        build: ./scripts
        ports:
            - "8080:80"
        volumes:
            - ./scripts:/app