version: "3.8"
services:
    proxy:
        image: nginx:alpine
        volumes:
            - ./configuration/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend
        tty: true
        networks:
            - waag

    frontend:
        build: ./frontend
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING="true"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        tty: true
        expose:
            - 3000
        networks:
            - waag

    backend:
        build: ./scripts
        volumes:
            - ./scripts:/app
        expose:
            - 80
        networks:
            - waag
networks:
    waag: