version: '3.8'
services:
    proxy:
        image: nginx:alpine
        volumes:
            - ./configuration/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/usr/share/nginx/html
            # - ./frontend/build:/etc/nginx/html/
        ports:
            - 80:80
        depends_on:
            - backend
        tty: true
        networks:
            - backend
    backend:
        build: 
            context: ./backend
            target: production_stage
        volumes:
            - ./backend:/app
        expose:
            - 80
        networks:
            - backend
        command: "/start.sh"
networks:
    backend:
