version: '3.8'
services:
    proxy:
        networks:
            - frontend
        depends_on:
            - frontend
        volumes:
            - ./configuration/nginx.local.conf:/etc/nginx/nginx.conf

    frontend:
        build: 
          context: ./frontend
          target: development_stage
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING="true"
            - REACT_APP_API=$API_ENDPOINT
        volumes:
            - ./frontend:/app
            - /app/node_modules
        tty: true
        expose:
            - 3000
        networks:
            - frontend

    backend:
        command: "/start-reload.sh"
networks:
    frontend: